apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: chat-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 88
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb:3306/drupal
        - name: SPRING_DATASOURCE_USERNAME
          value: drupal
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database-password
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
  - port: 88
    targetPort: 88
    nodePort: 30088
  type: NodePort 